INSERT INTO `User` (`username`, `password`) VALUES ('admin', '$2y$10$zVp9t1Aernk4oxSbMpBxrePWzwxUHq0szXuXgSGyCrKOLqRnrDHSu');

INSERT INTO `Category` (`name`, `slug`, `postCount`) VALUES ('PHP', 'php', '2');
INSERT INTO `Category` (`name`, `slug`, `postCount`) VALUES ('Javascript', 'javascript', '1');

INSERT INTO `Post` (`idUser`, `idCategory`, `name`, `slug`, `content`, `creationDate`) VALUES ('1', '1', 'Zend Validator', 'zend-validator', '## Lorem ipsum\n\nLorem ipsum dolor sit amet, consectetur adipisicing elit.\nCum esse exercitationem nam rem sed sunt totam ut velit.\nAccusamus accusantium, **cumque** illo inventore ipsa ipsam molestiae officia pariatur veniam voluptate?', '2017-08-20 10:05:22');
INSERT INTO `Post` (`idUser`, `idCategory`, `name`, `slug`, `content`, `creationDate`) VALUES ('1', '1', 'Zend Form', 'zend-form', 'fPHP Markdown to HTML converter\n------------------------------\n\n```php\n<?php\n\nnamespace Application\\Form;\n\n\nuse Zend\\Form\\Element\\Checkbox;\nuse Zend\\Form\\Element\\Email;\nuse Zend\\Form\\Element\\Password;\nuse Zend\\Form\\Form;\nuse Zend\\InputFilter\\Input;\n\nclass SignInForm extends Form\n{\n\n    /**\n     * {@inheritDoc}\n     */\n    public function __construct()\n    {\n        parent::__construct();\n\n        $this->add(new Email(\'email\'));\n        $this->add(new Password(\'password\'));\n        $this->add(new Checkbox(\'remember_me\'));\n\n        $inputFilter = $this->getInputFilter();\n\n        $emailInput = new Input(\'email\');\n        $emailInput->setRequired(true);\n        $inputFilter->add($emailInput);\n\n        $passwordInput = new Input(\'password\');\n        $passwordInput->setRequired(true);\n        $inputFilter->add($passwordInput);\n\n    }\n}\n```', '2017-08-22 15:18:25');
INSERT INTO `Post` (`idUser`, `idCategory`, `name`, `slug`, `content`, `creationDate`) VALUES ('1', '2', 'React', 'react', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum esse exercitationem nam rem sed sunt totam ut velit. Accusamus accusantium, cumque illo inventore ipsa ipsam molestiae officia pariatur veniam voluptate?', '2017-08-14 17:15:45');

INSERT INTO `Comment` (`idPost`, `username`, `email`, `content`, `creationDate`) VALUES ('1', 'John', 'john@doe.com', 'Un super article. Merci !', '2017-08-25 15:17:25');
INSERT INTO `Comment` (`idPost`, `username`, `email`, `content`, `creationDate`) VALUES ('2', 'Boby', 'boby@jones.com', 'Zend Form c\'est vraiment sympa !', '2017-08-26 15:46:08');