INSERT INTO `User` (`username`, `password`) VALUES ('admin', 'admin');

INSERT INTO `Category` (`name`, `slug`, `postCount`) VALUES ('PHP', 'php', '2');
INSERT INTO `Category` (`name`, `slug`, `postCount`) VALUES ('Javascript', 'javascript', '1');

INSERT INTO `Post` (`idUser`, `idCategory`, `name`, `slug`, `content`, `creationDate`) VALUES ('1', '1', 'Zend Validator', 'zend-validator', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum esse exercitationem nam rem sed sunt totam ut velit. Accusamus accusantium, cumque illo inventore ipsa ipsam molestiae officia pariatur veniam voluptate?', '2017-08-20 10:05:22');
INSERT INTO `Post` (`idUser`, `idCategory`, `name`, `slug`, `content`, `creationDate`) VALUES ('1', '1', 'Zend Form', 'zend-form', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus ad culpa dolore ipsum laudantium maiores recusandae reiciendis rerum temporibus? Accusamus consequatur exercitationem fuga hic ipsum molestiae nisi porro provident quod vero! Accusamus ad aut blanditiis consectetur cupiditate error et harum hic in iusto nesciunt nobis, odio officia quis quos ratione sapiente similique sint suscipit temporibus, ut veniam vero. Amet cupiditate doloremque laudantium mollitia nesciunt officia praesentium unde. Alias aliquid consequuntur eius esse et fuga molestias possimus praesentium quod! Blanditiis fuga sed ut veniam. Adipisci assumenda at consectetur doloribus dolorum eaque fugiat id, illum minus nam nisi non odit qui! Alias architecto consequuntur ea nesciunt quidem quod! A animi cum, ea ex exercitationem facere id in, necessitatibus odit perferendis, quo temporibus tenetur. Aliquam aspernatur dolore ea harum in minima non obcaecati recusandae suscipit tempore! Accusamus consectetur cum dignissimos et numquam omnis perferendis quod sint tenetur voluptates! Dignissimos earum ipsa, maxime perspiciatis repudiandae ullam. Deserunt illo ipsum magnam sint soluta! A ab accusantium ad consequuntur deleniti dignissimos dolores earum eius error exercitationem, fugiat id inventore magni molestiae nemo non nulla optio quae, sit sunt temporibus ut vitae voluptatum! Aliquid error esse, ex illo laboriosam modi, mollitia nostrum perspiciatis praesentium repellendus ullam velit.', '2017-08-22 15:18:25');
INSERT INTO `Post` (`idUser`, `idCategory`, `name`, `slug`, `content`, `creationDate`) VALUES ('1', '2', 'React', 'react', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum esse exercitationem nam rem sed sunt totam ut velit. Accusamus accusantium, cumque illo inventore ipsa ipsam molestiae officia pariatur veniam voluptate?', '2017-08-14 17:15:45');

INSERT INTO `Comment` (`idPost`, `username`, `email`, `content`, `creationDate`) VALUES ('1', 'John', 'john@doe.com', 'Un super article. Merci !', '2017-08-25 15:17:25');
INSERT INTO `Comment` (`idPost`, `username`, `email`, `content`, `creationDate`) VALUES ('2', 'Boby', 'boby@jones.com', 'Zend Form c\'est vraiment sympa !', '2017-08-26 15:46:08');