<div class="page-header">
    <h1>Blog</h1>
    <p class="lead">Welcome on my blog</p>
</div>

<?php if($this->posts->isNotEmpty()): ?>
    <?php
    /** @var \Application\Model\Infrastructure\View\Post\PostListItemView $post */
    foreach($this->posts as $post): ?>
        <article>
            <h2><a href="post.html"><?= $post->getName() ?></a></h2>
            <p><small>
                    Category : <a href="category.html"><?= $post->getCategory() ?></a>,
                    by <a href="index.html"><?= $post->getAuthor() ?></a> on <em><?= $post->getCreationDate()->format('M dS Y') ?></em>
                </small></p>
            <p><?= $post->getContent() ?></p>
            <p class="text-right"><a href="post.html" class="btn btn-primary">Read more...</a></p>
        </article>

        <hr>
    <?php endforeach; ?>
<?php else: ?>
    <p>No articles found</p>
<?php endif; ?>