<?php /** @var $post \Application\Model\Infrastructure\View\Post\PostView */ ?>
<div class="page-header">
    <h1><?=$post->getName() ?></h1>
    <p><small>
            Category : <a href="category.html"><?= $post->getCategory() ?></a>,
            by <a href="index.html"><?= $post->getAuthor() ?></a> on <em><?= $post->getCreationDate()->format('M dS Y') ?></em>
        </small></p>
</div>

<article><?= $this->markdown($post->getContent()); ?></article>

<hr>

<section class="comments">

    <h3>Comment this post</h3>

    <div class="alert alert-danger"><strong>Oh snap !</strong> you did some errors</div>

    <form role="form">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Your email">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group has-error">
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Your username">
                </div>
            </div>
        </div>
        <div class="form-group">
            <textarea class="form-control" rows="3" placeholder="Your comment"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <h3><?= $post->getCommentCount() . ' ' . $this->plural(['Comment', 'Comments'], $post->getCommentCount()) ?></h3>

    <?php if ($post->hasComments()): ?>
        <?php foreach($post->getComments() as $comment): /** @var \Application\Model\Infrastructure\View\Post\CommentView $comment */ ?>
            <div class="row">
                <?= ($comment !== $post->getComments()->first()) ? '<hr>' : '' ?>
                <div class="col-md-2">
                    <img src="http://lorempicsum.com/futurama/100/100/4" width="100%">
                </div>
                <div class="col-md-10">
                    <p><strong><?= $comment->getUsername() ?></strong> <?= $comment->getCreationDateToString() ?></p>
                    <p><?= $comment->getContent() ?></p>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</section>